services:
  users-api:
    image: victorhugojt/devops_rampup_users
    build: ./users-api
    environment:
      - JWT_SECRET=PRFT
      - SERVER_PORT=8083
  auth-api:
    image: victorhugojt/devops_rampup_auth
    build: ./auth-api/
    environment:
      - JWT_SECRET=PRFT
      - AUTH_API_PORT=8000
      - USERS_API_ADDRESS=http://users-api:8083
  redis:
    image: redis
  log-message-processor:
    image: victorhugojt/devops_rampup_log_processor
    build: ./log-message-processor
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_CHANNEL=log_channel
  todos-api:
    image: victorhugojt/devops_rampup_todos
    build: ./todos-api
    environment:
      - JWT_SECRET=PRFT
      - TODO_API_PORT=8082
      - REDIS_HOST=redis
      - REDIS_CHANNEL=log_channel
  frontend1:
    image: victorhugojt/devops_rampup_front
    build: ./frontend
    ports:
      - 8080:8080
    environment:
      - PORT=8080
      - AUTH_API_ADDRESS=http://auth-api:8000
      - TODOS_API_ADDRESS=http://todos-api:8082
  frontend2:
    image: victorhugojt/devops_rampup_front
    build: ./frontend
    ports:
      - 8081:8081
    environment:
      - PORT=8081
      - AUTH_API_ADDRESS=http://auth-api:8000
      - TODOS_API_ADDRESS=http://todos-api:8082
  nginx:
    image: victoremilio/devops_rampup_ngnix:1.0
    ports:
      - '80:80'
    depends_on:
      - frontend1
      - frontend2
