- hosts: host-auth
  become: yes
  become_user: root
  become_method: sudo

  vars:
    app_name: appAuth
    tag: 1.0
    users_api_adress: {{ hostvars['nodes'][0].ansible_host }}:8003
    jwt_secret: PRFT
    server_port: 8083
    auth_api_port: 8000

  tasks:
    - name: include role docker
      include_role:
        name: docker
    - name: include role clear-container
      include_role:
        name: clear-container

    - name: Execute docker container
      docker_container:
        name: "{{ app_name }}"
        image: victoremilio/devops_rampup_auth:{{ tag }}
        state: started
        restart_policy: unless-stopped
        pull: true
        published_ports:
          - "8000:8000"
        env:
          REDIS_PORT: "{{ redis_port }}"
          REDIS_HOST: "{{ redis_host }}"
          REDIS_CHANNEL: "{{ redis_channel }}"
          JWT_SECRET: "{{ jwt_secret }}"
          SERVER_PORT: "{{ server_port }}"
          AUTH_API_PORT: "{{ auth_api_port }}"
          USERS_API_ADDRESS: "{{ users_api_adress }}"