- hosts: frontend_host
  become: yes
  become_user: root
  become_method: sudo

  vars:
    app_name: appFrontend
    tag: "1.0"
    auth_api_adress: "{{ hostvars['host-auth'].ansible_host }}:8003"
    todo_api_adress: "{{ hostvars['todos_host'].ansible_host }}:8003"
    server_port: "8080"

  tasks:
    - name: include role docker
      include_role:
        name: docker
    - name: include role clear-container
      include_role:
        name: clear-container

    - name: Execute docker container
      docker_container:
        name: "{{ app_name }}"
        image: victoremilio/devops_rampup_front:{{ tag }}
        state: started
        restart_policy: unless-stopped
        pull: true
        published_ports:
          - "8080:8080"
        env:
          AUTH_API_ADDRESS: "{{ auth_api_adress }}"
          TODOS_API_ADDRESS: "{{ todo_api_adress }}"
          PORT: "{{ server_port }}"