- hosts: logs_host
  become: yes
  become_user: root
  become_method: sudo

  vars:
    app_name: appLogProcessor
    tag: 1.0
    redis_port: 6379
    redis_log_channel: log_channel
    jwt_secret: PRFT
    SERVER_PORT: 8083

  tasks:
    - name: include role docker
      include_role:
        name: docker
    - name: include role clear-container
      include_role:
        name: clear-container

    - name: Execute docker container
      docker_container:
        name: "{{ app_name }}"
        image: victoremilio/devops_rampup_log_processor:{{ tag }}
        state: started
        restart_policy: unless-stopped
        pull: true
        published_ports:
          - "8082:8082"
        env:
          REDIS_PORT: "{{ redis_port }}"
          REDIS_HOST: "{{ redis_host }}"
          REDIS_CHANNEL: "{{ redis_channel }}"
          JWT_SECRET: "{{ jwt_secret }}"
          SERVER_PORT: "{{ server_port }}"